name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the Crypto Art Discovery Zone'' first issue'
        pr-message: 'Thank you for contributing to the Discovery Zone'' first pr'
